### ISSUE TITLE
[BUG] There's an error while saving your birthday for the first time

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/BirthdayBot#11]
```
undefined
(node:56275) UnhandledPromiseRejectionWarning: ParallelSaveError: Can't save() the same doc multiple times in parallel. Document: 5f89926a6e3b4fdbd3d329bb
    at model.Model.save (/Users/tomassirio/Personal Projects/Bots/BirthdayBot/node_modules/mongoose/lib/model.js:463:20)
    at _callee$ (/Users/tomassirio/Personal Projects/Bots/BirthdayBot/build/commands/birthday.js:79:31)
    at tryCatch (/Users/tomassirio/Personal Projects/Bots/BirthdayBot/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/tomassirio/Personal Projects/Bots/BirthdayBot/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/tomassirio/Personal Projects/Bots/BirthdayBot/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/tomassirio/Personal Projects/Bots/BirthdayBot/build/commands/birthday.js:3:103)
    at _next (/Users/tomassirio/Personal Projects/Bots/BirthdayBot/build/commands/birthday.js:5:194)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:431:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:56275) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:56275) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by FabianBG** [comment]
Hi, triying to help for hacktoberfest :D check my pr https://github.com/tomassirio/BirthdayBot/pull/13
